### ISSUE TITLE
Unable to upload sounds

### ISSUE THREAD

**Issue by vaishalimutreja** [Portiloop/portiloop-software#9]
**Describe the bug**
We cannot upload new sounds in the Portiloop; even if it appears in the list, the size is 0. We also tried playing the new sounds with A play. We still hear nothing but the sounds which were already present in the sounds folder; it did play, but not the new ones.
Please note that we have used these new sounds previously in Portiloop; hence we know the sounds are OK. 

**To Reproduce**
1. Go to portiloop-software/portiloop/sounds
2. Click on upload
3. We see that the name of the sound but with size 0 

**Expected behavior**
The sounds upload and we can test it.

**Screenshots**

![soundUpload_notwork](https://github.com/Portiloop/portiloop-software/assets/67056914/c5cfe08c-20cc-4bef-a3df-a6ef3846d6c0)

**Hardware Info(please complete the following information):**
 - Portiloop version: v2.0
 - Release version of your code [write commit hash if not applicable]: Latest one
 - Host PC information: Windows PC + Microsoft Edge
 
**Additional context**
We are not sure whether this error is related to the fact that the notebook is not opening (please refer to our previous bug).

**Comment by milosobral** [comment]
Hi! I think both this issue and issue #8 are happening because the storage is full on your device. This is because the device actually uses a trash system where files are not directly removed from storage but are just moved to a different directory in case you want to recover them later. You can empty this trash directory with the following command: `rm -rf ~/.local/share/Trash/*`.

**Comment by vaishalimutreja** [comment]
> Hi! I think both this issue and issue #8 are happening because the storage is full on your device. This is because the device actually uses a trash system where files are not directly removed from storage but are just moved to a different directory in case you want to recover them later. You can empty this trash directory with the following command: `rm -rf ~/.local/share/Trash/*`.

Hi, 

It works now. Maybe you can add this in the documentation so that someone else don't face the same issue. 

If anything else comes to your mind that might cause a problem like notebook not loading or some sound issue then please let us know. 

Thank you,
Vaishali
